//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdt.CourseFinder.Migrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Insitutions = new HashSet<Insitution>();
        }
    
        public int CountryId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<Insitution> Insitutions { get; set; }
    }
}
