//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdt.CourseFinder.Migrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insitution
    {
        public Insitution()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int InsitutionId { get; set; }
        public string Name { get; set; }
        public string WebSite { get; set; }
        public int CountryId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CountryName { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
