//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdt.CourseFinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdt.CourseFinder.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Admin Role.
        /// </summary>
        internal static string AddedAdmin {
            get {
                return ResourceManager.GetString("AddedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another circle with this name already exists. Choose another name..
        /// </summary>
        internal static string CircleDuplicate {
            get {
                return ResourceManager.GetString("CircleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not yet registered.
        /// </summary>
        internal static string EmailNotReg {
            get {
                return ResourceManager.GetString("EmailNotReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your news. The news has been posted successfully. It shall be subjected to review before getting posted..
        /// </summary>
        internal static string NewsPostSuccess {
            get {
                return ResourceManager.GetString("NewsPostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks you for the offer. We have received your offer.  It shall be subjected to review before getting displayed on the website..
        /// </summary>
        internal static string OfferPostSuccess {
            get {
                return ResourceManager.GetString("OfferPostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Admin Role.
        /// </summary>
        internal static string RemovedAdmin {
            get {
                return ResourceManager.GetString("RemovedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Session Expired. Login agin..
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset token has expired. Kindly request a new token..
        /// </summary>
        internal static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised Acsess..
        /// </summary>
        internal static string UnAuthAccess {
            get {
                return ResourceManager.GetString("UnAuthAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised access by &apos;{0}&apos;.
        /// </summary>
        internal static string UnAuthAccessWithUser {
            get {
                return ResourceManager.GetString("UnAuthAccessWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was unblocked.
        /// </summary>
        internal static string UnblockedMsg {
            get {
                return ResourceManager.GetString("UnblockedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t find user the with ID &apos;{0}&apos;.
        /// </summary>
        internal static string UserNotFoundById {
            get {
                return ResourceManager.GetString("UserNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid date.
        /// </summary>
        internal static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
    }
}
