// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_milestone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_milestone));
        
        string IMigrationMetadata.Id
        {
            get { return "201403041421195_added_milestone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
