// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mile_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mile_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201403170634557_mile_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
