// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_visadetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_visadetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201406040952546_added_visadetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
