// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class milestone_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(milestone_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201403181125571_milestone_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
