// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_passport_return : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_passport_return));
        
        string IMigrationMetadata.Id
        {
            get { return "201406130440000_added_passport_return"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
