// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_userbranch_prjtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_userbranch_prjtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201407080532127_added_userbranch_prjtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
