// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_canditLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_canditLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201403060609555_add_canditLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
