// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class travelPostponement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(travelPostponement));
        
        string IMigrationMetadata.Id
        {
            get { return "201406090647509_travelPostponement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
