// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_candidateStaus_FK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_candidateStaus_FK));
        
        string IMigrationMetadata.Id
        {
            get { return "201403120643230_updated_candidateStaus_FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
