// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class category_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201403281417490_category_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
