// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_candit_ecCk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_candit_ecCk));
        
        string IMigrationMetadata.Id
        {
            get { return "201403200910026_updated_candit_ecCk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
