// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_visa_deposit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_visa_deposit));
        
        string IMigrationMetadata.Id
        {
            get { return "201406060439589_added_visa_deposit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
