// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_traveldetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_traveldetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201403311245099_added_traveldetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
