// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_Candit_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_Candit_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201403060621572_updated_Candit_10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
