// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_prjLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_prjLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201403030615549_added_prjLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
