// <auto-generated />
namespace Rdt.CourseFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_userLog_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_userLog_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201403140954405_updated_userLog_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
